version: 2
jobs:
  main:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.11.0
    steps:
      - checkout
      - run:
          name: Install yarn
          command: 'npm install --global yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - main
      