version: 2
jobs:
  main:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.11.0
    steps:
      - checkout

      - run:
          name: Install Latest Yarn
          command: npm install --global yarn

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          command: yarn lint
          name: Lint


workflows:
  version: 2
  test:
    jobs:
      - main

